apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: regsyncs.gounix.nl
spec:
  group: gounix.nl
  scope: Namespaced
  names:
    plural: regsyncs
    singular: regsync
    kind: Regsync
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              src:
                type: object
                properties:
                  registryName:
                    description: name of registry resource
                    type: string
                  imageRegex:
                    description: regex for the source image, if this is set image is ignored
                    type: string
                  image:
                    description: name of the image including namespace
                    type: string
                  tag:
                    description: tag of the image, can use regular expressions
                    type: string
                required:
                - registryName
                - image
                - tag
              filter:
                type: array
                description: list of architecture+os combinations to filter on, an empty filter selects all
                x-kubernetes-list-type: atomic
                items:
                  type: object
                  description: architecture+os combinations to filter on
                  properties:
                    architecture:
                      description: architecture to replicate (amd64, arm64, ..)
                      type: string
                    os:
                      description: os to replicate (linux, windows, ...)
                      type: string
              target:
                type: object
                properties:
                  registryName:
                    description: name of registry resource
                    type: string
                  base:
                    description: base directory where source image(including path) should be stored
                    type: string
                required:
                - registryName
                - base
    selectableFields:
    - jsonPath: .spec.src.registryName
    additionalPrinterColumns:
    - jsonPath: .spec.src.registryName
      name: "Src registry"
      type: string
    - jsonPath: .spec.src.image
      name: "Image"
      type: string
    - jsonPath: .spec.src.tag
      name: "Tag"
      type: string

