{
 "title": "Regsync dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "RegSync software", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "regsync_version", "legendFormat": "__auto" }
   ]
  },
  { "title": "Regsync stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "#Registries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(regsync_registries)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "#Configs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(regsync_configs)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Updated images",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(regsync_stats{updated=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not updated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(regsync_stats{updated=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(regsync_stats{err!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#garbage collected images",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(regsync_gc)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Regsync Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Registries",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      { "expr": "regsync_registries", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Configurations",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      { "expr": "regsync_configs", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Job status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Failed jobs",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "regsync_stats{err!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updated images",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "regsync_stats{updated=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collector activity",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "targets": [
    { "expr": "regsync_gc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "matches",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "regsync_matches", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    { "expr": "regsync_stats", "legendFormat": "__auto" }
   ]
  }
 ]
}