{{- range $v := .Values.regsync }}
---
apiVersion: gounix.nl/v1
kind: Regsync
metadata:
  name: {{ $v.name }}
spec:
  src:
    registryName: "{{ $v.src.registryName }}"
    imageRegex: '{{ $v.src.imageRegex }}'
    image: '{{ $v.src.image }}'
    tag: '{{ $v.src.tag }}'
  {{- if $v.filter }}
  filter:
    {{- with $v.filter }}
     {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  target:
    registryName: "{{ $v.target.registryName }}"
    base: "{{ $v.target.base }}"
{{- end }}
